<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\SalonApp.Modules.Services\SalonApp.Modules.Services.csproj" />
    <ProjectReference Include="..\..\SalonApp.Modules.Staff\SalonApp.Modules.Staff.csproj" />
    <ProjectReference Include="..\ClassLibrary1\SalonApp.Infratructure.csproj" />
    <ProjectReference Include="..\SalonApp.Modules.Appointments\SalonApp.Modules.Appointments.csproj" />
    <ProjectReference Include="..\SalonApp.Modules.Clients\SalonApp.Modules.Clients.csproj" />
    <ProjectReference Include="..\SalonApp.Modules.Notifications\SalonApp.Modules.Notifications.csproj" />
    <ProjectReference Include="..\SalonApp.SharedKernel\SalonApp.SharedKernel.csproj" />
  </ItemGroup>

</Project>
